[DPE-10948] feat: add rock

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,15 +41,89 @@ jobs:
       - name: Run linters
         run: just lint
 
-  build:
+  build-snap:
     name: Build snap
     uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v50.2.0
+
+  build-rock:
+    name: Build rock
+    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v50.2.0
+    with:
+      path-to-rock-directory: rock
 
   test-snap:
     name: Test Snap
     needs:
       - lint
-      - build
-    uses: ./.github/workflows/test-snap.yaml
+      - build-snap
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Install required dependencies
+        run: |
+          sudo snap install yq
+          pipx install rust-just
+          pipx install poetry
+
+      - name: Download snap package(s)
+        uses: actions/download-artifact@v4
+        with:
+          pattern: ${{ needs.build-snap.outputs.artifact-prefix }}-*
+          merge-multiple: true
+
+      - name: Install snap file
+        run: |
+          version="$(yq .version < snap/snapcraft.yaml)"
+          sudo snap install "cassandra_${version}_amd64.snap" --dangerous
+
+      - name: Connect required interfaces
+        run: |
+          just connect-interfaces
+          just sysctl-tuning
+
+      - name: Setup and Start Cassandra
+        run: |
+          sudo snap start cassandra.server
+          until sudo snap run cassandra.cassandra-nodetool status | grep -q "UN"; do
+              echo "Waiting for Cassandra to be ready..."
+              sleep 20s
+          done
+
+      - name: Ensure the cluster is reachable and node created via tests
+        run: just smoke
+
+      - name: Ensure configuration options are applied
+        run: just config
+
+      - name: Upgrade snap
+        run: |
+          version="$(yq .version < snap/snapcraft.yaml)"
+          sudo snap install "cassandra_${version}_amd64.snap" --dangerous
+
+          if [ -d /var/snap/cassandra/x2 ]; then
+              echo "Snap upgraded."
+          else
+              echo "Snap upgrade check failed: x2 revision directory not found."
+              exit 1
+          fi
+
+          sudo snap start cassandra.server
+          until sudo snap run cassandra.cassandra-nodetool status | grep -q "UN"; do
+              echo "Waiting for Cassandra to be ready..."
+              sleep 20s
+          done
+
+      - name: Ensure the cluster is reachable and node created after upgrade
+        run: just smoke
+
+  test-rock:
+    name: Test rock
+    needs:
+      - lint
+      - build-rock
+    uses: ./.github/workflows/test-rock.yaml
     with:
-      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
+      artifact-prefix: ${{ needs.build-rock.outputs.artifact-prefix }}-*
